mapbox/mapbox-data-team

package.json
=> Add test scripts

data/team.js
=> add two members in peru team

data/team.js
=> Added my name to the file.

data/team.js
=> Added my name in the list

README.md
- Corrected typo in package installation in `README`.
=> Updated data-team to mapbox-data-team

data/team.js
Added Gokul's name to the "data/team.js".
cc:// @arunasank
=> added Gokul's name to the mapbox-team-data

data/team.js, package.json, tests/test-data.js, tests/test.js
* other accounts
* clean up tests
* check for key validity
=> Other accounts

data/team.js, tests/test.js
Fixes #6
@geohacker - good to merge? cc @kepta
=> add github usernames for all team members

.gitignore, README.md, index.js, tests/test.js
- adds custom search option
- adds find and findOne
ref #17
=> add new find features

data/team.js
Added oormila to team.js .
@kepta Could you please look at this and merge it 🙏
=> Added oormila to team

data/team.js
@oormilavinod Changed the OSM username to be consistent for handles from `oormila` to `oormilavinod` . [OSM profile](https://www.openstreetmap.org/user/oormilavinod).
@kepta can you please look at this and merge.
cc @jothirnadh
=> updated oormila OSM username

data/team.js
=> add aj, ian, lukas

data/team.js
Would be great to have some of the directions crew who do map edits on here too
/cc @amishas157
=> Some more Mapboxers

data/team.js
Separate commit to re-format team.js - mixing tabs and spaces is bad for my ocd :D
=> Adds daniel-j-h to team.js

data/team.js
Add ingalls and sbma44 to data team
cc/ @geohacker @bsrinivasa
=> Add ingalls and sbma44 to data team

data/team.js
@kepta Can you take look at this PR and merge. Deploy it so that we can see their edits in OSM-Edit-Report and Dashboard.
cc @planemad @maning @poornibadrinath
=> Adding new members to the data team

data/team.js
Adding myself. 🙇
/cc @planemad
=> Add @friedbunny to team.js

README.md
closes https://github.com/mapbox/mapbox-data-team/issues/37
=> update README -- alpha not required

data/team.js
@planemad, I'm not sure what my UID is and/or where to find it....
=> Added self to team list

data/team.js
@kepta do you mind giving this a 👍 ?
=> adds mapbox machine user to user list
